apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: cip-keyless
spec:
  images:
    # All images in example repository matched
    - glob: "**"
  authorities:
    - keyless:
        # Signed by the public Fulcio certificate authority
        url: https://fulcio.sigstore.dev
        identities:
          # Matches the Github OIDC issuer
          - issuer: https://github.com/login/oauth
            subject: "hasan.hakkaev@gmx.at"
      ctlog:
        url: https://rekor.sigstore.dev
