apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: cip-key-secret
spec:
  mode: enforce
  images:
    - glob: "**"
  authorities:
    - key:
        secretRef:
          name: cosignsecret
